### ISSUE TITLE
Regular expressions must be properly quoted

### ISSUE THREAD

**Issue by brandes-pq** [hrennau/foxpath#2]
The quoting of the regular expressions that are generated for file name tests is incomplete. Characters that must be quoted but presently are not: `\`, `[`, `]`, `^`, `$`, `{`, `}`, `|`.

Example: matching a file named `a$b`

```sh
# fox -p '`a$b`'
<foxpathTree>
  <foxpath context="/Users/hauke/Projects/ParsQube/XML/foxpath" text="`a$b`">
    <foxStep axis="child" name="a$b" regex="^a$b$"/>
  </foxpath>
</foxpathTree>
```

**Comment by hrennau** [comment]
Many thanks, your detailed information was extremely helpful. Fixed.
