### ISSUE TITLE
A quoted file name test should not interpret wildcard characters

### ISSUE THREAD

**Issue by brandes-pq** [hrennau/foxpath#3]
It is not possible to match a file named `a*b` or `b?c`, as `*` and `?` are interpreted as wildcard characters:

```sh
# fox -p '`a*b`'
<foxpathTree>
  <foxpath context="/Users/hauke/Projects/ParsQube/XML/foxpath" text="`a*b`">
    <foxStep axis="child" name="a*b" regex="^a.*b$"/>
  </foxpath>
</foxpathTree>
```

... so the files `acb` or `acdb` would also match.

**Comment by hrennau** [comment]
Fixed - now you can specify * and ? in file names using `......` or ~* and ~?.
